<a href="https://colab.research.google.com/github/sushrutha777/WordEmbeding/blob/main/WordEmbeding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
## Define the vocabulary size
voc_size=10000

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[742, 5595, 2279, 5834],
 [742, 5595, 2279, 1296],
 [742, 7921, 2279, 6338],
 [1836, 4474, 3047, 4583, 8713],
 [1836, 4474, 3047, 4583, 2980],
 [1965, 742, 8767, 2279, 5645],
 [3283, 4878, 9652, 4583]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  742 5595 2279 5834]
 [   0    0    0    0  742 5595 2279 1296]
 [   0    0    0    0  742 7921 2279 6338]
 [   0    0    0 1836 4474 3047 4583 8713]
 [   0    0    0 1836 4474 3047 4583 2980]
 [   0    0    0 1965  742 8767 2279 5645]
 [   0    0    0    0 3283 4878 9652 4583]]


In [ ]:
## feature representation
dim=10

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,)))
model.compile(optimizer='adam', loss='mse')
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step


array([[[-3.31583507e-02, -4.71939817e-02, -2.33516935e-02,
          1.16543770e-02, -2.22753044e-02,  2.85901316e-02,
         -3.43125463e-02, -1.05748661e-02,  1.19261630e-02,
          3.51911895e-02],
        [-3.31583507e-02, -4.71939817e-02, -2.33516935e-02,
          1.16543770e-02, -2.22753044e-02,  2.85901316e-02,
         -3.43125463e-02, -1.05748661e-02,  1.19261630e-02,
          3.51911895e-02],
        [-3.31583507e-02, -4.71939817e-02, -2.33516935e-02,
          1.16543770e-02, -2.22753044e-02,  2.85901316e-02,
         -3.43125463e-02, -1.05748661e-02,  1.19261630e-02,
          3.51911895e-02],
        [-3.31583507e-02, -4.71939817e-02, -2.33516935e-02,
          1.16543770e-02, -2.22753044e-02,  2.85901316e-02,
         -3.43125463e-02, -1.05748661e-02,  1.19261630e-02,
          3.51911895e-02],
        [-9.60161537e-03,  2.66863964e-02, -6.11252710e-03,
          8.26819986e-03, -2.88719777e-02, -4.31438535e-03,
          1.31086446e-02, -3.02611236e-02,  1.776368

In [ ]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


array([[[-0.03315835, -0.04719398, -0.02335169,  0.01165438,
         -0.0222753 ,  0.02859013, -0.03431255, -0.01057487,
          0.01192616,  0.03519119],
        [-0.03315835, -0.04719398, -0.02335169,  0.01165438,
         -0.0222753 ,  0.02859013, -0.03431255, -0.01057487,
          0.01192616,  0.03519119],
        [-0.03315835, -0.04719398, -0.02335169,  0.01165438,
         -0.0222753 ,  0.02859013, -0.03431255, -0.01057487,
          0.01192616,  0.03519119],
        [-0.03315835, -0.04719398, -0.02335169,  0.01165438,
         -0.0222753 ,  0.02859013, -0.03431255, -0.01057487,
          0.01192616,  0.03519119],
        [-0.00960162,  0.0266864 , -0.00611253,  0.0082682 ,
         -0.02887198, -0.00431439,  0.01310864, -0.03026112,
          0.01776369, -0.0490048 ],
        [ 0.0163898 ,  0.0382187 , -0.0029055 ,  0.01567661,
         -0.04047311,  0.01773017,  0.02103906,  0.01313777,
         -0.01389705,  0.0258392 ],
        [ 0.01351681, -0.04389196,  0.00792367,  0.0